import { CanvasBlock, GitCommit, PresenceUser } from '@/types/builder';

export const INITIAL_BLOCKS: CanvasBlock[] = [
  {
    id: 'block-header',
    name: 'Header Navbar',
    type: 'header',
    layout: {
      x: 0,
      y: 0,
      width: '100%',
      height: 'auto',
      isLocked: false,
      isHidden: false,
    },
    style: {
      paddingTop: 16,
      paddingBottom: 16,
      paddingLeft: 24,
      paddingRight: 24,
      marginTop: 0,
      marginBottom: 0,
      backgroundColor: 'rgba(10, 13, 20, 0.7)',
      borderRadius: 16,
      borderColor: 'rgba(255, 255, 255, 0.08)',
      borderWidth: 1,
      opacity: 1,
      backdropBlur: 16,
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 24,
      maxWidth: '1200px',
    },
    content: {
      title: 'SYNAPSE AI',
      links: [
        { label: 'Architecture', href: '#architecture' },
        { label: 'Features', href: '#features' },
        { label: '3D Engine', href: '#3d' },
        { label: 'Pricing', href: '#pricing' },
      ],
      primaryCtaText: 'Launch Studio',
      secondaryCtaText: 'Sign In',
    },
  },
  {
    id: 'block-hero',
    name: 'Hero Section',
    type: 'hero',
    layout: {
      x: 0,
      y: 0,
      width: '100%',
      height: 'auto',
      isLocked: false,
      isHidden: false,
    },
    style: {
      paddingTop: 48,
      paddingBottom: 48,
      paddingLeft: 24,
      paddingRight: 24,
      marginTop: 8,
      marginBottom: 8,
      backgroundColor: 'transparent',
      borderRadius: 20,
      borderColor: 'rgba(255, 255, 255, 0.04)',
      borderWidth: 1,
      opacity: 1,
      backdropBlur: 0,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 24,
      maxWidth: '1200px',
    },
    content: {
      badgeText: '✨ v3.4 Engine — Next-Gen Spatial SaaS Architecture',
      title: 'Design Autonomous Software with',
      titleHighlight: 'Real-Time Spatial Intelligence',
      subtitle:
        'Eliminate engineering friction. Build, simulate, and deploy mission-critical edge interfaces with live 3D visual computing and instant agentic generation.',
      primaryCtaText: 'Deploy to Cloud — Free',
      secondaryCtaText: 'Watch Interactive Demo',
      elementStyles: {
        primaryCta: { hidden: true },
        secondaryCta: { hidden: true },
      },
    },
  },
  {
    id: 'block-3d-canvas',
    name: '3D Interactive Canvas Widget',
    type: 'canvas3d',
    layout: {
      x: 0,
      y: 0,
      width: '100%',
      height: 420,
      isLocked: false,
      isHidden: false,
    },
    style: {
      paddingTop: 16,
      paddingBottom: 16,
      paddingLeft: 16,
      paddingRight: 16,
      marginTop: 0,
      marginBottom: 16,
      backgroundColor: 'rgba(13, 17, 27, 0.65)',
      borderRadius: 24,
      borderColor: 'rgba(99, 102, 241, 0.25)',
      borderWidth: 1,
      opacity: 1,
      backdropBlur: 20,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 12,
      maxWidth: '1200px',
    },
    content: {
      badgeText: 'WebGL 3D Neural Gizmo Active',
      title: 'Interactive 3D Geometry Core',
      subtitle: 'Drag to rotate • Scroll to zoom • Spatial shaders in real time',
    },
    threeConfig: {
      meshType: 'torusKnot',
      wireframe: false,
      glassFactor: 0.85,
      rotationSpeed: 0.8,
      floatSpeed: 1.2,
      lightIntensity: 1.5,
      color: '#6366f1',
      glowColor: '#a855f7',
      rx: 20,
      ry: 35,
      rz: 15,
      scale: 1,
      particleCount: 80,
      showGizmo: true,
    },
  },
  {
    id: 'block-2d-canvas',
    name: '2D Vector Graphics Studio',
    type: 'canvas2d',
    layout: {
      x: 0,
      y: 0,
      width: '100%',
      height: 'auto',
      isLocked: false,
      isHidden: false,
    },
    style: {
      paddingTop: 16,
      paddingBottom: 16,
      paddingLeft: 16,
      paddingRight: 16,
      marginTop: 0,
      marginBottom: 16,
      backgroundColor: 'rgba(13, 17, 27, 0.65)',
      borderRadius: 24,
      borderColor: 'rgba(99, 102, 241, 0.25)',
      borderWidth: 1,
      opacity: 1,
      backdropBlur: 20,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 12,
      maxWidth: '1200px',
    },
    content: {
      title: 'Studio Vectoriel 2D',
      subtitle: 'Concevez, animez & exportez vos tracés géométriques',
    },
    twoConfig: {
      shapes: [
        { id: 'initial-rect', type: 'rect', x: 50, y: 50, size: 30, width: 30, height: 30, fill: '#6366f1', stroke: '#ffffff', strokeWidth: 2, rotation: 45, opacity: 0.95, glow: true, glowColor: '#6366f1', animType: 'spin', animSpeed: 1 },
        { id: 'initial-circle', type: 'circle', x: 30, y: 35, size: 20, fill: '#ec4899', stroke: '#ffffff', strokeWidth: 2, rotation: 0, opacity: 0.9, glow: true, glowColor: '#ec4899', animType: 'float', animSpeed: 1.2 },
        { id: 'initial-star', type: 'star', x: 70, y: 35, size: 22, fill: '#f59e0b', stroke: '#ffffff', strokeWidth: 1.5, rotation: 15, opacity: 0.95, glow: true, glowColor: '#f59e0b', animType: 'bounce', animSpeed: 1 }
      ],
      backgroundColor: '#0d111b',
      showGrid: true,
      themePreset: 'custom'
    },
  },
  {
    id: 'block-features',
    name: 'Feature Bento Grid',
    type: 'featureGrid',
    layout: {
      x: 0,
      y: 0,
      width: '100%',
      height: 'auto',
      isLocked: false,
      isHidden: false,
    },
    style: {
      paddingTop: 48,
      paddingBottom: 48,
      paddingLeft: 24,
      paddingRight: 24,
      marginTop: 8,
      marginBottom: 8,
      backgroundColor: 'transparent',
      borderRadius: 20,
      borderColor: 'transparent',
      borderWidth: 0,
      opacity: 1,
      backdropBlur: 0,
      display: 'grid',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'stretch',
      gap: 20,
      maxWidth: '1200px',
    },
    content: {
      badgeText: 'Enterprise Capabilities',
      title: 'Engineered for Unmatched Velocity',
      subtitle: 'Every layer built for seamless collaboration, sub-10ms feedback loops, and production-grade reliability.',
      gridColumns: 3,
      features: [
        {
          id: 'feat-1',
          icon: 'Boxes',
          title: 'Spatial 3D Viewport',
          description: 'Render high-poly meshes, procedural shaders, and physics simulations directly within your UI canvas.',
          tag: 'WebGL 2.0',
        },
        {
          id: 'feat-2',
          icon: 'GitBranch',
          title: 'Visual Git Branching',
          description: 'Branch UI states, merge visual pull requests with pixel-diff inspection, and revert with zero data loss.',
          tag: 'Non-Destructive',
        },
        {
          id: 'feat-3',
          icon: 'Bot',
          title: 'Agent Code Assistant',
          description: 'Translate natural language prompts into production React, Tailwind CSS, and WebGL state changes in milliseconds.',
          tag: 'Autonomous AI',
        },
        {
          id: 'feat-4',
          icon: 'Zap',
          title: 'Zero-Latency Sync',
          description: 'Multi-cursor collaborative canvas with distributed CRDT state synchronization across worldwide teams.',
          tag: '<8ms Latency',
        },
        {
          id: 'feat-5',
          icon: 'ShieldCheck',
          title: 'Cryptographic Security',
          description: 'Isolated container sandboxes, automated vulnerability auditing, and enterprise SOC2 compliant vaults.',
          tag: 'SOC2 Ready',
        },
        {
          id: 'feat-6',
          icon: 'Code2',
          title: 'Live Next.js Export',
          description: 'Clean, idiomatic TypeScript and Tailwind CSS exportable at any millisecond with one click.',
          tag: 'Production Output',
        },
      ],
    },
  },
  {
    id: 'block-pricing',
    name: 'Pricing Tier Section',
    type: 'pricing',
    layout: {
      x: 0,
      y: 0,
      width: '100%',
      height: 'auto',
      isLocked: false,
      isHidden: false,
    },
    style: {
      paddingTop: 48,
      paddingBottom: 48,
      paddingLeft: 24,
      paddingRight: 24,
      marginTop: 8,
      marginBottom: 8,
      backgroundColor: 'rgba(11, 15, 24, 0.4)',
      borderRadius: 24,
      borderColor: 'rgba(255, 255, 255, 0.06)',
      borderWidth: 1,
      opacity: 1,
      backdropBlur: 16,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 32,
      maxWidth: '1200px',
    },
    content: {
      badgeText: 'Transparent Pricing',
      title: 'Predictable Scale for Bold Builders',
      subtitle: 'Start free, upgrade as your user base and computing workload explode.',
      pricingPlans: [
        {
          id: 'plan-starter',
          name: 'Developer',
          priceMonthly: 0,
          priceAnnual: 0,
          description: 'Ideal for indie hackers, prototyping, and personal experiments.',
          features: [
            'Up to 3 Active Projects',
            'Standard 3D WebGL Canvas',
            '50 AI Agent Prompts / mo',
            'Community Support',
            'Public Git History',
          ],
          ctaText: 'Start Free',
        },
        {
          id: 'plan-pro',
          name: 'Pro Studio',
          priceMonthly: 39,
          priceAnnual: 29,
          description: 'For growing teams building commercial SaaS and high-traffic web applications.',
          features: [
            'Unlimited Canvas Projects',
            'Full 3D Shaders & Gizmo Tooling',
            'Unlimited Agent Prompts',
            'Team Live Collaboration (10 seats)',
            'Direct Next.js / GitHub Push',
            'Priority 24/7 SLA Support',
          ],
          isPopular: true,
          ctaText: 'Upgrade to Pro',
        },
        {
          id: 'plan-enterprise',
          name: 'Enterprise Cloud',
          priceMonthly: 129,
          priceAnnual: 99,
          description: 'Dedicated cloud computing cluster with custom security SLAs.',
          features: [
            'Dedicated Private GPU Workers',
            'Custom AI Fine-Tuned Models',
            'Unlimited Team Members',
            'SSO / SAML & Audit Logs',
            'Custom Domain CDN Edge',
            'Dedicated Account Architect',
          ],
          ctaText: 'Contact Sales',
        },
      ],
    },
  },
  {
    id: 'block-footer',
    name: 'Footer Section',
    type: 'footer',
    layout: {
      x: 0,
      y: 0,
      width: '100%',
      height: 'auto',
      isLocked: false,
      isHidden: false,
    },
    style: {
      paddingTop: 32,
      paddingBottom: 32,
      paddingLeft: 24,
      paddingRight: 24,
      marginTop: 16,
      marginBottom: 0,
      backgroundColor: 'rgba(8, 10, 16, 0.85)',
      borderRadius: 16,
      borderColor: 'rgba(255, 255, 255, 0.05)',
      borderWidth: 1,
      opacity: 1,
      backdropBlur: 12,
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 16,
      maxWidth: '1200px',
    },
    content: {
      title: 'opendesign',
      subtitle: 'The open standard for next-generation visual software development.',
      copyrightText: '© 2026 opendesign Inc. All systems operational • Global Edge v3.4',
    },
  },
];

export const INITIAL_GIT_COMMITS: GitCommit[] = [
  {
    id: 'c-1',
    hash: 'a9f214e',
    message: 'feat: add interactive 3D WebGL hero element with spatial gizmo',
    branch: 'main',
    author: 'Leo Kross',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    timestamp: '14 min ago',
    diffCount: 14,
    snapshot: INITIAL_BLOCKS,
  },
  {
    id: 'c-2',
    hash: '8cb301d',
    message: 'style(bento): convert feature section to 3-column glass layout',
    branch: 'main',
    author: 'Sarah Chen',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    timestamp: '42 min ago',
    diffCount: 6,
    snapshot: INITIAL_BLOCKS,
  },
  {
    id: 'c-3',
    hash: '4e29bb1',
    message: 'ai: optimize CTA contrast & annual billing discount badge',
    branch: 'feat/v2-pricing',
    author: 'OpenDesign AI Agent',
    avatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    timestamp: '2 hours ago',
    diffCount: 3,
    snapshot: INITIAL_BLOCKS,
  },
  {
    id: 'c-4',
    hash: '109ff62',
    message: 'init: scaffold SaaS project structure with glassmorphism layout',
    branch: 'main',
    author: 'Alex Vance',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    timestamp: '5 hours ago',
    diffCount: 32,
    snapshot: INITIAL_BLOCKS,
  },
];

export const INITIAL_PRESENCE: PresenceUser[] = [
  {
    id: 'u-1',
    name: 'Sarah Chen',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    color: '#06b6d4',
    activeBlockId: 'block-hero',
    status: 'Editing Hero Headline',
  },
  {
    id: 'u-2',
    name: 'Leo Kross',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    color: '#8b5cf6',
    activeBlockId: 'block-3d-canvas',
    status: 'Tuning 3D Gizmo Shaders',
  },
  {
    id: 'u-3',
    name: 'Alex Vance',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    color: '#10b981',
    activeBlockId: 'block-features',
    status: 'Viewing Bento Layout',
  },
  {
    id: 'u-ai',
    name: 'OpenDesign AI',
    avatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    color: '#ec4899',
    activeBlockId: null,
    status: 'Ready for prompts',
  },
];
